language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# before_install:

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install wheel

# before_script:

# command to run tests
script:
  - python PythonHelpers/unit_tests/tests_main.py

# after_success:

# after_failure:

# after_script:

before_deploy:
  - python setup.py bdist_wheel
  # Set up git user name and tag this commit
  - git config --local user.name "LostInDarkMath"
  - git config --local user.email "32729196+LostInDarkMath@users.noreply.github.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases  # use Github pages instead: pages 
  github_token: $GITHUB_TOKEN
  file: dist/PythonHelpers-1.0.0-py3-none-any.whl
  skip_cleanup: true
  overwrite: true
  # on:
    # tags: true

# after_deploy:
